baseURL = 'https://nprezant.github.io/laurenzitney.com/'
languageCode = 'en-us'
title = "Lauren Zitney"
theme = "med"

# https://gohugo.io/content-management/menus/
[menu]
[[menu.main]]
  name = 'lauren zitney'
  pageRef = '/'
  weight = 10
[[menu.main]]
  name = 'posts'
  pageRef = '/posts'
  weight = 20
[[menu.main]]
  name = 'about'
  pageRef = '/about'
  weight = 30

# To allow building restructured text
[security.exec]
  allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^npx$', '^postcss$', '^rst2html$', '^rst2html.py$', '^asciidoctor$']

# Default home page config
[params]
  homeTitle = 'Welcome.'
  homeSubtitle = 'Enjoy.'

# Taxonomies
[taxonomies]
  tag = 'tags'

# Allows looking in the static dir for assets
# [module]
# [[module.mounts]]
#   source = 'static'
#   target = 'assets'
